<a href="https://colab.research.google.com/github/JAGUAR1617/LSTM-timeseries/blob/main/lstm_timeseries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [30]:

# LSTM for international airline passengers problem with window regression framing
import numpy
import matplotlib.pyplot as plt
from pandas import read_csv
import math
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error


In [31]:
# convert an array of values into a dataset matrix
def create_dataset(dataset, look_back=1):
	dataX, dataY = [], []
	for i in range(len(dataset)-look_back-1):
		a = dataset[i:(i+look_back), 0]
		dataX.append(a)
		dataY.append(dataset[i + look_back, 0])
	return numpy.array(dataX), numpy.array(dataY)


In [40]:
# fix random seed for reproducibility
numpy.random.seed(7)



In [46]:
# load the dataset
dataset = [110,125,133,146,158,172,187,196,210]
arr = numpy.array(dataset)
dataset = numpy.reshape(arr, (arr.shape[0], 1))

In [47]:
X, y = create_dataset(dataset, 3)


In [48]:
X, y

(array([[110, 125, 133],
        [125, 133, 146],
        [133, 146, 158],
        [146, 158, 172],
        [158, 172, 187]]), array([146, 158, 172, 187, 196]))

In [49]:
X.shape

(5, 3)

In [50]:
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

In [51]:
y.shape

(5,)

In [53]:
# define model
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(3, 1)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=50, verbose=1)

Epoch 1/50
1/1 [==============================] - 2s 2s/step - loss: 27799.0000
Epoch 2/50
1/1 [==============================] - 0s 12ms/step - loss: 27003.3711
Epoch 3/50
1/1 [==============================] - 0s 11ms/step - loss: 26271.5410
Epoch 4/50
1/1 [==============================] - 0s 8ms/step - loss: 25602.5410
Epoch 5/50
1/1 [==============================] - 0s 8ms/step - loss: 24952.5684
Epoch 6/50
1/1 [==============================] - 0s 12ms/step - loss: 24280.0156
Epoch 7/50
1/1 [==============================] - 0s 10ms/step - loss: 23549.1348
Epoch 8/50
1/1 [==============================] - 0s 12ms/step - loss: 22726.2695
Epoch 9/50
1/1 [==============================] - 0s 13ms/step - loss: 21814.5625
Epoch 10/50
1/1 [==============================] - 0s 13ms/step - loss: 20887.0469
Epoch 11/50
1/1 [==============================] - 0s 18ms/step - loss: 20014.7500
Epoch 12/50
1/1 [==============================] - 0s 10ms/step - loss: 19207.7480
Epoch 13/50
1/1 [

In [57]:
import numpy as np

In [83]:
input = np.array([187, 196, 210])

In [86]:
input.shape

(3,)

In [87]:
input.shape

(3,)

In [89]:
input = numpy.reshape(input, (input.shape[0], 1))

In [92]:
input.shape

(3, 1)

In [98]:
input = numpy.reshape(input, (input.shape[0], 1, input.shape[1]))


In [102]:
input = input.reshape((1, 3, 1))

In [103]:
input.shape

(1, 3, 1)

In [104]:
model.predict(input)

array([[229.0432]], dtype=float32)

In [105]:
# similary for last three number next predictions can be made 

In [106]:
input = np.array([187, 196, 210])
input = numpy.reshape(input, (input.shape[0], 1))
input = numpy.reshape(input, (input.shape[0], 1, input.shape[1]))
input = input.reshape((1, 3, 1))
model.predict(input)


array([[229.0432]], dtype=float32)

In [107]:
input = np.array([196, 210, 229.0432])
input = numpy.reshape(input, (input.shape[0], 1))
input = numpy.reshape(input, (input.shape[0], 1, input.shape[1]))
input = input.reshape((1, 3, 1))
model.predict(input)

array([[243.33766]], dtype=float32)

In [108]:
input = np.array([210, 229.0432, 243.33766])
input = numpy.reshape(input, (input.shape[0], 1))
input = numpy.reshape(input, (input.shape[0], 1, input.shape[1]))
input = input.reshape((1, 3, 1))
model.predict(input)

array([[261.71237]], dtype=float32)

In [109]:
# we can use for loop to predict 10 series

In [111]:
# demonstrate prediction for next 10 days
x_input = np.array([229.0432, 243.33766, 261.71237])
temp_input=list(x_input)
lst_output=[]
for i in range(10):
    if(len(temp_input)>3):
        x_input=np.array(temp_input[1:])
        print(x_input)
        print("{} day input {}".format(i,x_input))
        #print(x_input)
        x_input = x_input.reshape((1, 3, 1))
        #print(x_input)
        yhat = model.predict(x_input, verbose=0)
        print("{} day output {}".format(i,yhat))
        temp_input.append(yhat[0][0])
        temp_input=temp_input[1:]
        #print(temp_input)
        lst_output.append(yhat[0][0])
    else:
        x_input = x_input.reshape((1, 3, 1))
        yhat = model.predict(x_input, verbose=0)
        print(yhat[0])
        temp_input.append(yhat[0][0])
        lst_output.append(yhat[0][0])
    

print(lst_output)

[282.5293]
[243.33766    261.71237    282.52929688]
1 day input [243.33766    261.71237    282.52929688]
1 day output [[302.1276]]
[261.71237    282.52929688 302.12759399]
2 day input [261.71237    282.52929688 302.12759399]
2 day output [[324.95398]]
[282.5293  302.1276  324.95398]
3 day input [282.5293  302.1276  324.95398]
3 day output [[349.54874]]
[302.1276  324.95398 349.54874]
4 day input [302.1276  324.95398 349.54874]
4 day output [[374.80045]]
[324.95398 349.54874 374.80045]
5 day input [324.95398 349.54874 374.80045]
5 day output [[402.87234]]
[349.54874 374.80045 402.87234]
6 day input [349.54874 374.80045 402.87234]
6 day output [[432.82492]]
[374.80045 402.87234 432.82492]
7 day input [374.80045 402.87234 432.82492]
7 day output [[464.53723]]
[402.87234 432.82492 464.53723]
8 day input [402.87234 432.82492 464.53723]
8 day output [[499.0629]]
[432.82492 464.53723 499.0629 ]
9 day input [432.82492 464.53723 499.0629 ]
9 day output [[535.9243]]
[282.5293, 302.1276, 324.9539

In [65]:
# x_input = np.array([187, 196, 210])
# temp_input=list(x_input)
# lst_output=[]


In [113]:
# next 10 digit series
print(lst_output)

[282.5293, 302.1276, 324.95398, 349.54874, 374.80045, 402.87234, 432.82492, 464.53723, 499.0629, 535.9243]
